[package]
name = "agent-store"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.17.0"
borsh = "0.10.3"
thiserror = "1.0.40"

[lib]
crate-type = ["cdylib", "lib"]
